= Appendicies

include::attributes.adoc[]

== Java API

We keep a recent link available here to the most recently built and deployed
link:apidocs/index.html[Java API Documentation] for {qr-name}.

== AMQP Resources & Formats

:AMQP: https://www.rabbitmq.com/protocol.html

The declared {AMQP}[AMQP] broker resources is kept to a minimum. Only two
exchanges are declared, one for the data-plane and one for a control-plane. By
default these are `query-response` and the `query-response.fanout`, with both
names being configurable.

All Query/Response client services will automatically declare or connect to
the required exchanges, with the following parameters:

....
  name: query-response
  type: topic
  durable: true
  auto-delete: false
....

....
  name: query-response.fanout
  type: fanout
  durable: true
  auto-delete: false
....

The Query/Response library defines a small set of properties and data-formats,
which are used in the AMQP messages - a mini-protocol if you wish.

=== Query messages

Query messages are very simple in structure and form. The common
`query-response` exchanged is published to, and the message `routing-key` will
carry the specific `query-term` that is requested. The `reply-to` header
property is set to the queue name of a generated `query-response-queue`,
specific to the published query.

Both query and response messages use the `application/json` content-type. There
is no further content in the body, but **always** an empty JSON object `{}`, as
a placeholder for future capabilities.

....
  exchange: query-response
  routing-key: ${query-term}
  reply-to: ${query-response-queue}
  content-type: application/json
  body:
  {}
....

=== Response messages

Published responses also use a common format. They are published to the empty
(default) exchange, with the `query-response-queue` from the `reply-to`
property of a consumed query as the `routing-key`. This will cause a direct
routing of responses back to the declared response-queue.

The response body payload JSON structure always wraps the `elements` collection
containing the actual response data in an _envelope object_.

....
  exchange: (default)
  routing-key: ${query-response-queue}
  content-type: application/json
  body:
  {
    elements: [...]
  }
....

The current properties of Query/Response messages are simple but provide
room for extensions in future versions.

== Trademarks

:Oracle: https://www.oracle.com

{java-name} is a registered trademark of {Oracle}[Oracle] and/or its affiliates.
Other names may be trademarks of their respective owners.

:Pivotal: https://www.pivotal.io

{spring-name} and {spring-boot-name} are trademarks of {Pivotal}[Pivotal]
Software, Inc. in the U.S. and other countries.
